export const defaultUsers = [
  {
    id: 1,
    name: 'Aarav Mehta',
    email: 'admin@library.com',
    password: 'Admin@123',
    role: 'admin',
    department: 'Library Administration',
    membershipId: 'ADM-101',
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 2,
    name: 'John',
    email: 'student@library.com',
    password: 'Student@123',
    role: 'user',
    department: 'Computer Science',
    membershipId: 'STD-204',
    avatar: '',
  },
  {
    id: 3,
    name: 'Rohan Verma',
    email: 'rohan@college.edu',
    password: 'User@123',
    role: 'user',
    department: 'Electronics',
    membershipId: 'STD-327',
    avatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
  },
];

export const defaultBooks = [
  {
    id: 101,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    category: 'Programming',
    status: 'Issued',
    description: 'A handbook of agile software craftsmanship.',
  },
  {
    id: 102,
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    category: 'Computer Science',
    status: 'Available',
    description: 'Algorithm design, analysis, and implementation.',
  },
  {
    id: 103,
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    category: 'Design',
    status: 'Available',
    description: 'Human-centered design principles for products and systems.',
  },
  {
    id: 104,
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    category: 'Database',
    status: 'Issued',
    description: 'Core concepts in database architecture and queries.',
  },
  {
    id: 105,
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Self Development',
    status: 'Available',
    description: 'Practical techniques for building good habits.',
  },
  {
    id: 106,
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell',
    category: 'AI',
    status: 'Available',
    description: 'Comprehensive introduction to AI concepts and systems.',
  },
];

export const defaultTransactions = [
  {
    id: 9001,
    bookId: 101,
    userId: 2,
    bookTitle: 'Clean Code',
    borrower: 'John',
    issueDate: '2026-04-04',
    dueDate: '2026-04-18',
    returnDate: '',
    fine: 20,
    status: 'Issued',
  },
  {
    id: 9002,
    bookId: 104,
    userId: 3,
    bookTitle: 'Database System Concepts',
    borrower: 'Rohan Verma',
    issueDate: '2026-04-07',
    dueDate: '2026-04-21',
    returnDate: '',
    fine: 0,
    status: 'Issued',
  },
  {
    id: 9003,
    bookId: 105,
    userId: 2,
    bookTitle: 'Atomic Habits',
    borrower: 'John',
    issueDate: '2026-03-10',
    dueDate: '2026-03-24',
    returnDate: '2026-03-23',
    fine: 0,
    status: 'Returned',
  },
];
